routes/web.php
<?php

use App\Http\Controllers\Admin\InfoController;
use App\Models\Info;
use Illuminate\Support\Facades\Route;


Route::view('/', 'welcome', ['info' => Info::query()->first()])
    ->name('welcome');

Route::view('/dashboard', 'dashboard')
    ->name('admin.dashboard');

Route::middleware([])
    ->name('admin.')
    ->group(function () {
        Route::resource('infos', InfoController::class);
    });

app/Models/Info.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'nom',
        'prenom',
        'pseudo',
        'email',
        'telephone',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
    ];
}

app/Http/Controllers/Admin/InfoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Info;
use Illuminate\Http\Request;

class InfoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $info = Info::query()->first();
        return view('admin.infos.index', compact('info'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.infos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Info::query()->create([
            'nom' => $request->nom,
            'slogan' => $request->slogan,
            'hero_title' => $request->hero_title,
            'hero_desc' => $request->hero_desc,
            'adresse' => $request->adresse,
            'email' => $request->email,
            'telephone' => $request->telephone,
            'facebook' => $request->facebook,
            'twitter' => $request->twitter,
            'whatsapp' => $request->whatsapp,
            'youtube' => $request->youtube,
            'apropos' => $request->apropos,
        ]);

        // toastr()->info('L\'info a été ajoutée avec succès !!!');
        return to_route('admin.infos.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Info  $info
     * @return \Illuminate\Http\Response
     */
    public function edit(Info $info)
    {
        if ($info) {
            return view('admin.infos.edit', compact('info'));
        } else {
            // toastr()->error('L\'info selectionnée n\'existe pas !!!');
            return back();
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Info  $info
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Info $info)
    {
        $info->update([
            'nom' => $request->nom,
            'slogan' => $request->slogan,
            'hero_title' => $request->hero_title,
            'hero_desc' => $request->hero_desc,
            'adresse' => $request->adresse,
            'email' => $request->email,
            'telephone' => $request->telephone,
            'facebook' => $request->facebook,
            'twitter' => $request->twitter,
            'whatsapp' => $request->whatsapp,
            'youtube' => $request->youtube,
            'apropos' => $request->apropos,
        ]);
        return to_route('admin.infos.index')->with('info', 'Les informations ont été modifiée avec succès !!!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/infos/edit.blade.php
@extends('admin.layouts.app')

@section('admin.content')
<section class="bg-white mx-auto shadow-lg">
  <div class="text-center mb-4">
    <h2 class="text-xl font-semibold capitalize underline tracking-wider leading-relaxed">Modifier les infos de
      l'entreprise</h2>
  </div>
  <div class="mx-4">
    <form action="{{ route('admin.infos.update', $info) }}" method="post">
      @csrf @method('PUT')
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="nom" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider"> Nom de
            l'entreprise</label>
          <input type="text" id="nom" name="nom" value="{{ old('nom') ?? $info->nom }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="slogan" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Slogan</label>
          <input type="text" id="slogan" name="slogan" value="{{ old('slogan') ?? $info->slogan }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
      </div>
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="adresse"
            class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Adresse</label>
          <input type="text" id="adresse" name="adresse" value="{{ old('adresse') ?? $info->adresse }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="telephone"
            class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Telephone</label>
          <input type="text" id="telephone" name="telephone" value="{{ old('telephone') ?? $info->telephone }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
      </div>
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="email" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Email</label>
          <input type="email" id="email" name="email" value="{{ old('email') ?? $info->email }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="facebook" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Lien vers la
            page Facebook</label>
          <input type="text" id="facebook" name="facebook" value="{{ old('facebook') ?? $info->facebook }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
      </div>
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="twitter" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Lien vers la
            page Twitter</label>
          <input type="text" id="twitter" name="twitter" value="{{ old('twitter') ?? $info->twitter }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="whatsapp" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Lien vers la
            page Whatsapp</label>
          <input type="text" id="whatsapp" name="whatsapp" value="{{ old('whatsapp') ?? $info->whatsapp }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
      </div>
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="youtube" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Lien vers la
            page Youtube</label>
          <input type="text" id="youtube" name="youtube" value="{{ old('youtube') ?? $info->youtube }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="hero_title" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Titre
            d'accueil</label>
          <input type="text" id="hero_title" name="hero_title" value="{{ old('hero_title') ?? $info->hero_title }}"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full">
        </div>
      </div>
      <div class="lg:flex justify-between items-center mb-6">
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="hero_desc" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">Message
            d'accueil</label>
          <textarea name="hero_desc" id="hero_desc" cols="30" rows="10"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full text-justify">{{ old('hero_desc') ?? $info->hero_desc }}</textarea>
        </div>
        <div class="w-full mr-4 mb-4 lg:mb-0">
          <label for="apropos" class="text-gray-600 text-lg block font-semibold capitalize tracking-wider">A Propos de
            L'entreprise</label>
          <textarea name="apropos" id="apropos" cols="30" rows="10"
            class="px-4 py-2 border border-gray-300 rounded-lg text-gray-600 text-md tracking-wider focus:outline-none w-full text-justify">{{ old('apropos') ?? $info->apropos }}</textarea>
        </div>
      </div>
      <div class="flex place-content-center pb-6">
        <button type="submit"
          class="px-4 py-2 rounded-lg w-1/2 text-white bg-indigo-700 hover:bg-indigo-500 font-bold tracking-widest text-xl">
          <i class="fa fa-check mr-2"></i>
          <span>Valider</span>
        </button>
      </div>
    </form>
  </div>
</section>
@endsection

resources/views/admin/infos/index.blade.php
@extends('admin.layouts.app')

@section('admin.content')

<section class="bg-white flex flex-col lg:flex-row p-2">
  <div class="bg-gray-200 shadow-lg w-full lg:w-1/3">
    <div class="">
      <img src="{{ asset('logo.jpeg') }}" class="">
    </div>
    <ul class="bg-white p-2 m-3">
      <h2 class="text-lg capitalize text-center underline text-gray-700 mb-2">
        Les réseaux sociaux
      </h2>
      <li class="border-2 border-separate border-gray-600 text-gray-600 rounded-md px-4 py-2 mb-3 break-words">
        <i class="fa fa-at"></i>
        <span>{{ $info->email }}</span>
      </li>
      <li class="border-2 border-separate border-teal-600 text-teal-600 rounded-md px-4 py-2 mb-3">
        <i class="fa fa-phone-alt"></i>
        <span>{{ $info->telephone }}</span>
      </li>
      <li class="text-sm border-2 border-separate border-blue-600 text-blue-600 rounded-md px-4 py-2 mb-3 break-words">
        <i class="fab fa-facebook"></i>
        <span>{{ $info->facebook }}</span>
      </li>
      <li
        class="text-sm border-2 border-separate border-green-600 text-green-600 rounded-md px-4 py-2 mb-3 break-words">
        <i class="fab fa-whatsapp"></i>
        <span>{{ $info->whatsapp }}</span>
      </li>
      <li class="text-sm border-2 border-separate border-cyan-600 text-cyan-600 rounded-md px-4 py-2 mb-3 break-words">
        <i class="fab fa-twitter"></i>
        <span>{{ $info->twitter }}</span>
      </li>
      <li class="text-sm border-2 border-separate border-red-600 text-red-600 rounded-md px-4 py-2 mb-3 break-words">
        <i class="fab fa-youtube"></i>
        <span class="">{{ $info->youtube }}</span>
      </li>
    </ul>
  </div>
  <div class="bg-gray-200 shadow-lg p-4 w-full lg:w-2/3">
    <div class="flex lg:flex-row flex-col-reverse justify-between">
      <div class="w-full lg:w-4/6">
        <h1
          class="text-xl text-indigo-800 text-center font-bold font-mono uppercase underline tracking-widest leading-loose mb-2">
          {{ $info->nom }}
        </h1>
        <h6 class="text-xs text-center text-gray-600 uppercase mb-5">"
          {{ $info->slogan }}
          "</h6>
        <h6 class="text-base text-center mb-3">
          {{ $info->adresse }}
        </h6>
      </div>
      <div class="hidden lg:block w-2/6">
        <a href="{{ route('admin.infos.edit', $info) }}" class="ml-4 text-xs bg-blue-700 hover:bg-blue-500 text-white px-4 py-2 w-1/2 text-center float-right">
          <i class="fa fa-edit"></i>
          <span>Editer</span>
        </a>
      </div>
    </div>
    <div class="bg-white border-2 border-gray-500 rounded-lg py-1 px-2 mb-3">
      <h2 class="text-lg font-semibold capitalize text-center underline text-gray-700 mb-2">
        A propos de l'entreprise
      </h2>
      <p class="text-base text-justify">
        {{ $info->apropos }}
      </p>
    </div>
    <div class="bg-white border-2 border-gray-500 rounded-lg py-1 px-2 ">
      <h2 class="text-lg font-semibold capitalize text-center underline text-gray-700 mb-2">
        Le héro section
      </h2>
      <div class="">
        <h4 class="text-base capitalize text-justify font font-semibold underline mb-2">
          {{ $info->hero_title }}
        </h4>
      </div>
      <div class="">
        <p class="text-base text-justify">
          {{ $info->hero_desc }}
        </p>
      </div>
    </div>
  </div>
</section>


@endsection

resources/views/admin/infos/menu.blade.php
<a href="{{ route('admin.infos.index') }}" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
  <i class="fas fa-info-circle mr-3"></i>
  Info
</a>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.name') }}">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tailwind Admin Template</title>
  <meta name="author" content="David Grzyb">
  <meta name="description" content="">

  <!-- Tailwind -->
  <link href="{{ mix('css/app.css') }}" rel="stylesheet">
  <script src="//unpkg.com/alpinejs" defer></script>
  <style>
    .bg-sidebar {
      background: #3d68ff;
    }

    .cta-btn {
      color: #3d68ff;
    }

    .active-nav-link {
      background: #1947ee;
    }

    .nav-item:hover {
      background: #1947ee;
    }

    .account-link:hover {
      background: #3d68ff;
    }
  </style>
</head>

<body class="bg-gray-100 font-family-karla flex">

  @include('admin.partials.sidebar')

  <div class="w-full flex flex-col h-screen overflow-y-hidden">

    @include('admin.partials.header')

    <div class="w-full overflow-x-hidden border-t flex flex-col">
      <main class="w-full flex-grow p-6 relative">

        @if (session('info'))
        <div x-data="{ show: true }" x-show="show" x-init="setTimeout(() => show = false, 3000)"
          class="absolute top-0 grid place-content-center">
          <div class="px-4 py-3 text-sm rounded-full shadow-lg bg-green-400 text-white font-semibold font-mono">
            {{ session('info') }}
          </div>
        </div>
        @endif

        @yield('admin.content')

      </main>

      <footer class="w-full bg-white text-right p-4">
        Produit par <span class="text-2xl underline">TAOB</span>.
      </footer>
    </div>

  </div>

  <!-- AlpineJS -->
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  <!-- Font Awesome -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
    integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
  <!-- ChartJS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"
    integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>

  <script>
    var chartOne = document.getElementById('chartOne');
        var myChart = new Chart(chartOne, {
            type: 'bar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        var chartTwo = document.getElementById('chartTwo');
        var myLineChart = new Chart(chartTwo, {
            type: 'line',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
  </script>
</body>

</html>

resources/views/admin/partials/header.blade.php
<!-- Desktop Header -->
<header class="w-full items-center bg-white py-2 px-6 hidden sm:flex">
  <div class="w-1/2"></div>
  <div x-data="{ isOpen: false }" class="relative w-1/2 flex justify-end">
    <button @click="isOpen = !isOpen"
      class="realtive z-10 w-12 h-12 rounded-full overflow-hidden border-4 border-gray-400 hover:border-gray-300 focus:border-gray-300 focus:outline-none">
      <img src="https://source.unsplash.com/uJ8LNVCBjFQ/400x400">
    </button>
    <button x-show="isOpen" @click="isOpen = false" class="h-full w-full fixed inset-0 cursor-default"></button>
    <div x-show="isOpen" class="absolute w-32 bg-white rounded-lg shadow-lg py-2 mt-16">
      <a href="#" class="block px-4 py-2 account-link hover:text-white">Account</a>
      <a href="#" class="block px-4 py-2 account-link hover:text-white">Support</a>
      <a href="#" class="block px-4 py-2 account-link hover:text-white">Sign Out</a>
    </div>
  </div>
</header>

<!-- Mobile Header & Nav -->
<header x-data="{ isOpen: false }" class="w-full bg-sidebar py-5 px-6 sm:hidden">
  <div class="flex items-center justify-between">
    <a href="index.html" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">Admin</a>
    <button @click="isOpen = !isOpen" class="text-white text-3xl focus:outline-none">
      <i x-show="!isOpen" class="fas fa-bars"></i>
      <i x-show="isOpen" class="fas fa-times"></i>
    </button>
  </div>

  <!-- Dropdown Nav -->
  <nav :class="isOpen ? 'flex': 'hidden'" class="flex flex-col pt-4">
    <a href="index.html" class="flex items-center active-nav-link text-white py-2 pl-4 nav-item">
      <i class="fas fa-tachometer-alt mr-3"></i>
      Dashboard
    </a>
    <a href="blank.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-sticky-note mr-3"></i>
      Blank Page
    </a>
    <a href="tables.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-table mr-3"></i>
      Tables
    </a>
    <a href="forms.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-align-left mr-3"></i>
      Forms
    </a>
    <a href="tabs.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-tablet-alt mr-3"></i>
      Tabbed Content
    </a>
    <a href="calendar.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-calendar mr-3"></i>
      Calendar
    </a>
    <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-cogs mr-3"></i>
      Support
    </a>
    <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-user mr-3"></i>
      My Account
    </a>
    <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
      <i class="fas fa-sign-out-alt mr-3"></i>
      Sign Out
    </a>
    <button
      class="w-full bg-white cta-btn font-semibold py-2 mt-3 rounded-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
      <i class="fas fa-arrow-circle-up mr-3"></i> Upgrade to Pro!
    </button>
  </nav>
  <!-- <button class="w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
                <i class="fas fa-plus mr-3"></i> New Report
            </button> -->
</header>

resources/views/admin/partials/sidebar.blade.php
<aside class="relative bg-sidebar h-screen w-64 hidden sm:block shadow-xl">
  <div class="p-6">
    <a href="#" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">
      Admin
    </a>
  </div>
  <nav class="text-white text-base font-semibold pt-3">
    <a href="index.html" class="flex items-center active-nav-link text-white py-4 pl-6 nav-item">
      <i class="fas fa-tachometer-alt mr-3"></i>
      Dashboard
    </a>

    @include('admin.infos.menu')

  </nav>
</aside>

resources/views/dashboard.blade.php
@extends('admin.layouts.app')

resources/views/partials/footer.blade.php
<footer class="relative bg-gray-300 pt-8 pb-6">
  <div class="bottom-auto top-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden -mt-20"
    style="height: 80px;">
    <svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"
      version="1.1" viewBox="0 0 2560 100" x="0" y="0">
      <polygon class="text-gray-300 fill-current" points="2560 0 2560 100 0 100"></polygon>
    </svg>
  </div>
  <div class="container mx-auto px-4">
    <div class="flex flex-wrap">
      <div class="w-full px-4">
        <h4 class="text-3xl font-semibold">Gardons le contact !</h4>
        <h5 class="text-lg mt-0 mb-2 text-gray-700">
          Trouvez-nous sur chacune de ces plateformes, on répond à vos differentes requêtes ...
        </h5>
        <div class="flex justify-between items-center">
          <div class="mt-6">
            <a href="{{ $info->twitter }}">
              <button
                class="bg-white text-blue-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                type="button">
                <i class="flex fab fa-twitter"></i>
              </button>
            </a>
            <a href="{{ $info->facebook }}">
              <button
                class="bg-white text-blue-600 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                type="button">
                <i class="flex fab fa-facebook-square"></i>
              </button>
            </a>
            <a href="{{ $info->whatsapp }}">
              <button
                class="bg-white text-green-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                type="button">
                <i class="flex fab fa-whatsapp"></i>
              </button>
            </a>
            <a href="mailto:{{ $info->youtube }}">
              <button
                class="bg-white text-red-900 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                type="button">
                <i class="flex fab fa-youtube"></i>
              </button>
            </a>
          </div>
          <div class="text-xl px-3 py-1 bg-gray-100">
            <span class="fa fa-at"> : <strong>{{ $info->email }}</strong> </span>
          </div><div class="text-xl px-3 py-1 bg-gray-100">
            <span class="fa fa-phone-alt"> : <strong>{{ $info->telephone }}</strong> </span>
          </div>
        </div>
      </div>
    </div>
    <hr class="my-6 border-gray-400" />
    <div class="flex flex-wrap items-center md:justify-between justify-center">
      <div class="w-full md:w-4/12 px-4 mx-auto text-center">
        <div class="text-sm text-gray-600 font-semibold uppercase py-1">
          Copyright &COPY;
          {{ now()->year . ' - ' . $info->nom }} par
          <span class="text-blue-700 text-2xl">TAOB</span>
        </div>
      </div>
    </div>
  </div>
</footer>